DEFAULT_NOTICE = (
    "This content was generated by an AI system and routed through "
    "Overflow governance middleware. Verify critical information before use."
)


def apply_watermark(text, notice=None):
    suffix = notice or DEFAULT_NOTICE
    return text + "\n\n" + suffix
